### ISSUE TITLE
S3 object and methods to support synthetic data

### ISSUE THREAD

**Issue by Naeemkh** [NSAPH-Software/CRE#17]
The synthetic data requires methods to support summary, print, and plot functions.

**Comment by riccardocadei** [comment]
Why should the synthetic data require the plot function?
Are you referring to CRE outcome instead?

**Comment by Naeemkh** [comment]
It would be good to give a quick and dirty plot to the user to have an idea bout the synthetic data.

**Comment by Naeemkh** [comment]
Closing for now. No need to have this feature at this point.
