### ISSUE TITLE
Output Error if no Causal Decision Rules are selected

### ISSUE THREAD

**Issue by riccardocadei** [NSAPH-Software/CRE#51]
If no Causal Decision Rules is extracted we still pretend to return all the outputs, but all the variables defined on the inference subsample (i.e. ite_inf) are not defined yet (see [line](https://github.com/riccardocadei/CRE/blob/a090cf9d6cad1c491bc57b0ffdd351d6bcf3b99d/R/cre.R#L147)). Should we compute them anyway or avoid to return them?

**Comment by fbargaglistoffi** [comment]
Great point, @riccardocadei. I believe that in this case we should just compute the Average Treatment Effect (ATE) and return a warning message saying something along the lines of “No heterogeneity was detected.”
