### ISSUE TITLE
Not documented error Hyper Parameters accepted values

### ISSUE THREAD

**Issue by riccardocadei** [NSAPH-Software/CRE#53]
Not all the combination of `q` and `pfer_val` for the penalized regression for rule section are allowed. For example setting `q=0.51` and `pfer_val=0.1` in _test-cre.R_ I get the following error:
```
Error in uniroot(function(q) q^2/p/um_const(cutoff, B, theta = q/p) - : 
f() values at end points not of opposite sign
``` 
It is due to the function [stabsel](https://www.rdocumentation.org/packages/stabs/versions/0.6-4/topics/stabsel) in the package stabs. These constraints should be studied and added to _check_hyper_params.R_.

**Comment by Naeemkh** [comment]
@riccardocadei, Handling all possible combinations might not be practical. You may try to put it in a tryCatch block and terminate it gracefully with and informative error message.

**Comment by riccardocadei** [comment]
Added tryCatch.
